### PR TITLE
Handle variable report_data index sizes

### LINKED ISSUE #61: write_nv_index size issue
## Description

It appears there is some issue with write_nv_index. It seems like for the [None case](https://github.com/kinvolk/azure-cvm-tooling/blob/f273ba9e4c4d80fbd6769210f8e90731f1f5edd8/az-cvm-vtpm/src/vtpm/mod.rs#L158) it uses owner_nv_public, which will [check the data length](https://github.com/kinvolk/azure-cvm-tooling/blob/f273ba9e4c4d80fbd6769210f8e90731f1f5edd8/az-cvm-vtpm/src/vtpm/mod.rs#L147). However, for the Some case the data length doesn't seemed to be checked.

## Impact

In the downstream guest-components repo, this is causing issues with passing in runtime data / report data. See https://github.com/confidential-containers/guest-components/issues/765

## Environment and steps to reproduce

See https://github.com/confidential-containers/guest-components/issues/765 for test cases that reproduce the bug in the downstream repo. 

One thing to note is this bug seems to involve TPM state. I believe you need to first give some report data of a short length (e.g. 11 bytes) and then try to run the code again with runtime data that is longer (e.g. 12 bytes). Running `sudo tpm2_nvundefine -C o 0x01400002` seemed to reset the state for me so I could use a longer input. 

## Expected behavior

You can pass in runtime data of different lengths without having to reset each time

### PR DESCRIPTION
**Pull request by mkulke**
# Handle variable report_data index sizes

fixes #61

A caller of `get_report_with_report_data()` might provide report_data of varying sizes. We need to verify the size of the allocated nv index that holds the report data and recreate it if necessary.

## How to use

Should introduce no breaking change, run the integration test on CVM hardware to confirm. Can be built locally and then copied over: 

```bash
cargo test --all --features integration_test --no-run
...
scp target/debug/deps/integration_tests-... azureuser@...:
ssh azureuser@...
sudo ./integration_tests-... --test-threads 1
```

## Testing done

Integration tests have been added to test this on CVM hardware.

### CODE REVIEW

File: az-cvm-vtpm/src/vtpm/mod.rs [hunk 1]
```diff
@@ -107,62 +108,103 @@ pub fn get_report() -> Result<Vec<u8>, ReportError> {
...
+) -> Result<(), ReportError> {
+    let buffer = MaxNvBuffer::try_from(data)?;
+    let result = find_index(context, handle, data.len())?;
+    let index = match result {
+        NvSearchResult::NotFound => create_index(context, handle, data.len())?,
+        NvSearchResult::SizeMismatch => {
+            delete_index(context, handle)?;
+            create_index(context, handle, data.len())?
+        }
+        _ => resolve_handle(context, handle)?,
```
Comment (jepio) [inline az-cvm-vtpm/src/vtpm/mod.rs:204]: would it make sense for this to be an explicit `NvSearchResult::Found`?

**Review by jepio — DISMISSED** [review]

**Review by jepio — APPROVED** [review]
